import type { Metadata } from "next";
import localFont from "next/font/local";
import { Poppins, Tilt_Warp } from "next/font/google";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const tiltWarp = Tilt_Warp({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-tilt-warp',
  display: 'swap',
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-poppins',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${tiltWarp.variable} ${poppins.variable} font-poppins antialiased min-h-screen bg-gradient-to-b from-white via-green-100 to-purple-100`}
      >
        {children}
      </body>
    </html>
  );
}
